[project]
name = "funes"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Francisco Perez-Sorrosal", email = "fperezsorrosal@gmail.com"}]
requires-python = ">= 3.11"
dependencies = ["rich", "dspy-ai", "ipykernel"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
funes = { path = ".", editable = true }

[tool.pixi.tasks]
funes = "python funes"

[tool.pixi.dependencies]
jinja2 = ">=3.1.4,<3.2"

[tool.setuptools]
py-modules = []
